using OnlineMuhasebe.Domain.CompanyEntities;
using OnlineMuhasebe.Domain.Repositories.UniformChartOfAccountRepositories;
using OnlineMuhasebe.Persistence.Repositories.GenericRepositories.CompanyDbContextRepositories;

namespace OnlineMuhasebe.Persistence.Repositories.UniformCharOfAccountRepositories;

public class UniformChartOfAccountCommandRepository : CompanyCommandRepository<UniformChartOfAccount>, IUniformChartOfAccountCommandRepository
{
}
