using OnlineMuhasebe.Domain.CompanyEntities;
using OnlineMuhasebe.Domain.Repositories.GenericRepositories.CompanyDbContextRepositories;

namespace OnlineMuhasebe.Domain.Repositories.CompanyDbContextRepositories.UniformChartOfAccountRepositories;

public interface IUniformChartOfAccountCommandRepository : ICompanyDbCommandRepository<UniformChartOfAccount>
{
}
