using OnlineMuhasebe.Domain.CompanyEntities;

namespace OnlineMuhasebe.Domain.Repositories.CompanyDbContextRepositories.UniformChartOfAccountRepositories;

public interface IUniformChartOfAccountQueryRepository : ICompanyDbQueryRepository<UniformChartOfAccount>
{
}
